// This file was generated by Firebase Genkit.
'use server';

/**
 * @fileOverview Identifies food items from an image.
 *
 * - identifyFoodItems - A function that identifies food items in an image.
 * - IdentifyFoodItemsInput - The input type for the identifyFoodItems function.
 * - IdentifyFoodItemsOutput - The return type for the identifyFoodItems function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const IdentifyFoodItemsInputSchema = z.object({
  photoUrl: z.string().describe('The URL of the food image.'),
});
export type IdentifyFoodItemsInput = z.infer<typeof IdentifyFoodItemsInputSchema>;

const IdentifyFoodItemsOutputSchema = z.object({
  foodItems: z
    .array(z.string())
    .describe('The identified food items in the image.'),
});
export type IdentifyFoodItemsOutput = z.infer<typeof IdentifyFoodItemsOutputSchema>;

export async function identifyFoodItems(input: IdentifyFoodItemsInput): Promise<IdentifyFoodItemsOutput> {
  return identifyFoodItemsFlow(input);
}

const identifyFoodItemsPrompt = ai.definePrompt({
  name: 'identifyFoodItemsPrompt',
  input: {
    schema: z.object({
      photoUrl: z.string().describe('The URL of the food image.'),
    }),
  },
  output: {
    schema: z.object({
      foodItems: z
        .array(z.string())
        .describe('The identified food items in the image.'),
    }),
  },
  prompt: `You are an expert at identifying food items in images.

  Based on the image provided, identify the food items present.

  Image: {{media url=photoUrl}}
  `, 
});

const identifyFoodItemsFlow = ai.defineFlow<
  typeof IdentifyFoodItemsInputSchema,
  typeof IdentifyFoodItemsOutputSchema
>({
  name: 'identifyFoodItemsFlow',
  inputSchema: IdentifyFoodItemsInputSchema,
  outputSchema: IdentifyFoodItemsOutputSchema,
}, async input => {
  const {output} = await identifyFoodItemsPrompt(input);
  return output!;
});