name: Next.js CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GOOGLE_GENAI_API_KEY: ${{ secrets.GOOGLE_GENAI_API_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Lint
      run: npm run lint

    - name: Type Check
      run: npm run typecheck

    - name: Build Next.js App
      run: npm run build

    - name: Build Docker image
      run: docker build -t nextjs-food-app .
